import SiteNav from '../../components/SiteNav';
import SiteFooter from '../../components/SiteFooter';

export default function TermsPage() {
  return (
    <div className="bg-ink text-paper min-h-screen">
      <SiteNav />
      <section className="px-6 md:px-12 py-16 max-w-2xl mx-auto">
        <h1 className="font-display text-5xl tracking-wide mb-2">Terms &amp; Conditions</h1>
        <p className="font-mono text-xs text-paper/40 mb-8">Last updated: [DATE]</p>

        <div className="space-y-6 font-body text-paper/80 leading-relaxed">
          <p>
            These Terms &amp; Conditions ("Terms") govern your use of [COMPANY NAME]
            ("we", "us", "the Service"), accessible via [WEBSITE URL]. By creating an
            account or using the Service, you agree to these Terms.
          </p>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">1. The Service</h2>
            <p>
              The Service allows you to upload photos and receive AI-generated
              entertainment content (jokes, roasts, captions, ratings, and similar
              outputs) based on those photos. Outputs are generated automatically by
              AI models and are provided for entertainment purposes only.
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">2. Eligibility</h2>
            <p>
              You must be at least [MINIMUM AGE, e.g. 13 or 18 depending on jurisdiction]
              years old to use the Service. By using the Service, you confirm you meet
              this requirement. [Note: confirm the correct minimum age for your
              jurisdiction and target markets with legal counsel.]
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">3. Your Content</h2>
            <p>
              You retain ownership of any photo you upload. By uploading a photo, you
              grant us a limited license to process it through our AI systems and
              store it as described in our Privacy Policy, solely to provide the
              Service to you. You confirm you have the right to upload each photo,
              including consent from anyone else identifiable in it.
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">4. Acceptable Use</h2>
            <p>
              You agree not to upload photos of anyone without their consent, upload
              content that is illegal, abusive, or infringing, or attempt to misuse
              the Service to generate harmful, harassing, or exploitative content
              about yourself or others.
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">5. Subscriptions &amp; Payments</h2>
            <p>
              Paid plans are billed as described at checkout. Payments are processed
              by our third-party payment provider. See our{' '}
              <a href="/refund" className="text-marigold hover:underline">Refund Policy</a>{' '}
              for cancellation and refund terms.
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">6. AI-Generated Content Disclaimer</h2>
            <p>
              Outputs are generated by AI and are for entertainment only. They do not
              constitute professional advice of any kind and may be inaccurate,
              exaggerated, or nonsensical by design.
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">7. Termination</h2>
            <p>
              We may suspend or terminate your account for violation of these Terms.
              You may delete your account at any time from Settings.
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">8. Limitation of Liability</h2>
            <p>
              The Service is provided "as is" without warranties of any kind. To the
              maximum extent permitted by law, [COMPANY NAME] is not liable for any
              indirect, incidental, or consequential damages arising from your use of
              the Service.
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">9. Governing Law</h2>
            <p>
              These Terms are governed by the laws of [JURISDICTION, e.g. India].
            </p>
          </div>

          <div>
            <h2 className="font-display text-2xl tracking-wide text-paper mb-2">10. Contact</h2>
            <p>
              Questions about these Terms? Reach us at [SUPPORT EMAIL] or via our{' '}
              <a href="/contact" className="text-marigold hover:underline">Contact page</a>.
            </p>
          </div>

          <p className="text-sm text-paper/40 italic pt-4 border-t border-paper/10">
            This is a template and not legal advice. Have a lawyer review and
            customize it before publishing — especially the sections on minimum age,
            photo/consent handling, and payment/refund terms, since these carry real
            legal obligations in most jurisdictions.
          </p>
        </div>
      </section>
      <SiteFooter />
    </div>
  );
}
